### ISSUE TITLE
ImportError: cannot import name 'bpy_helper' from 'bpyhullsim.bpyutils' (unknown location)

### ISSUE THREAD

**Issue by pafurijaz** [edzop/bpyhullsim#2]
Hi also this addon has the same issue of  **bpyhullgen** 
```
Traceback (most recent call last):
  File "/home/user-pf/Software/blender-2.93.0/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/user-pf/.config/blender/2.93/scripts/addons/bpyhullsim/__init__.py", line 39, in <module>
    from .hullsim import sim_helper
  File "/home/user-pf/.config/blender/2.93/scripts/addons/bpyhullsim/hullsim/sim_helper.py", line 6, in <module>
    from ..bpyutils import bpy_helper
ImportError: cannot import name 'bpy_helper' from 'bpyhullsim.bpyutils' (unknown location)


```

**Comment by pafurijaz** [comment]
I think this is solved with the same solution by downloading the missing file for helper.
